// Tactical Volley – Karten-Konfiguration
const CARDS = {
  outside: {
    label_de: "Aussenangreifer",
    label_en: "Outside Hitter",
    color: "#e84317",
    colorDark: "#2d0f0f",
    folder: "images/Aussen",
    files: [
      "outside_01.png",
      "outside_02.png",
      "outside_03.png",
      "outside_04.png",
      "outside_05.png",
      "outside_06.png",
      "outside_07.png",
      "outside_08.png",
      "outside_09.png",
      "outside_10.png",
      "outside_11.png",
      "outside_12.png",
      "outside_13.png",
      "outside_14.png",
      "outside_15.png",
      "outside_16.png",
      "outside_17.png",
      "outside_18.png",
      "outside_19.png",
      "outside_20.png",
      "outside_21.png",
      "outside_22.png",
      "outside_23.png",
      "outside_24.png",
      "outside_25.png",
      "outside_26.png",
      "outside_27.png",
      "outside_28.png",
      "outside_29.png",
    ]
  },
  diagonal: {
    label_de: "Diagonalangreifer",
    label_en: "Diagonal",
    color: "#4f46e5",
    colorDark: "#0d0e2d",
    folder: "images/Diagonal",
    files: [
      "diagonal_01.png",
      "diagonal_02.png",
      "diagonal_03.png",
      "diagonal_04.png",
      "diagonal_05.png",
      "diagonal_06.png",
      "diagonal_07.png",
      "diagonal_08.png",
      "diagonal_09.png",
      "diagonal_10.png",
      "diagonal_11.png",
      "diagonal_12.png",
      "diagonal_13.png",
      "diagonal_14.png",
      "diagonal_15.png",
      "diagonal_16.png",
      "diagonal_17.png",
      "diagonal_18.png",
      "diagonal_19.png",
    ]
  },
  libero: {
    label_de: "Libero",
    label_en: "Libero",
    color: "#ca8a04",
    colorDark: "#2a2000",
    folder: "images/Liberos",
    files: [
      "libero_01.png",
      "libero_02.png",
      "libero_03.png",
      "libero_04.png",
      "libero_05.png",
      "libero_06.png",
      "libero_07.png",
      "libero_08.png",
      "libero_09.png",
      "libero_10.png",
      "libero_11.png",
      "libero_12.png",
      "libero_13.png",
      "libero_14.png",
      "libero_15.png",
      "libero_16.png",
      "libero_17.png",
      "libero_18.png",
    ]
  },
  middle: {
    label_de: "Mittelblocker",
    label_en: "Middle Blocker",
    color: "#16a34a",
    colorDark: "#0d2a0d",
    folder: "images/Mitte",
    files: [
      "middle_01.png",
      "middle_02.png",
      "middle_03.png",
      "middle_04.png",
      "middle_05.png",
      "middle_06.png",
      "middle_07.png",
      "middle_08.png",
      "middle_09.png",
      "middle_10.png",
      "middle_11.png",
      "middle_12.png",
      "middle_13.png",
      "middle_14.png",
      "middle_15.png",
      "middle_16.png",
      "middle_17.png",
      "middle_18.png",
      "middle_19.png",
      "middle_20.png",
      "middle_21.png",
      "middle_22.png",
      "middle_23.png",
      "middle_24.png",
      "middle_25.png",
    ]
  },
  setter: {
    label_de: "Zuspieler",
    label_en: "Setter",
    color: "#0ea5e9",
    colorDark: "#0d1a2d",
    folder: "images/Passeur",
    files: [
      "setter_01.png",
      "setter_02.png",
      "setter_03.png",
      "setter_04.png",
      "setter_05.png",
      "setter_06.png",
      "setter_07.png",
      "setter_08.png",
      "setter_09.png",
      "setter_10.png",
      "setter_11.png",
      "setter_12.png",
      "setter_13.png",
      "setter_14.png",
      "setter_15.png",
      "setter_16.png",
      "setter_17.png",
      "setter_18.png",
      "setter_19.png",
    ]
  },
};